
sudo: required
language: java

jdk:
  - openjdk8

script:
  - mvn clean compile assembly:single

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/build-test-conflicts/neo4j/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-b7510993703e48a4f5a744d7bd7cc20869b6bf14
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            